%% The following function imports and compares 2 codon usage datatables %%
%% As an output, it generates a bargraph of codon usage ratio and a scatter plot of the raw data %%
% REM: this function only works with a matrix generated by "Fun_Fred_CodonAnalysis.m" function or equivalent cell array structure

function Fun_Fred_Codontable_comparison(Table1,Table2,lgd)

% Generate the data to plot
labels = cell2mat(Table2(2:62,1));
Freq1 = cell2mat(Table1(2:62,4));
Freq2 = cell2mat(Table2(2:62,4));
x = 1:length(Freq1);
n = length(Freq1);
font = 11;

% Generate ratio data figure
x0 = 10;y0 = 10;width = 1500; height = 750;
figure;set(gcf,'position',[x0,y0,width,height]);
subplot(2,1,1);
ylbl = ('Synonymous codon usage ratios');
titlelbl = ('Ratios');
barcolor = [0.750000000000000,0.750000000000000,0.750000000000000;];
Fun_Fred_vertical_bargraphs(Freq1./Freq2,labels,ylbl,titlelbl,barcolor);
ylim([0 3]);xlim([0 n+1]);hold on;
plot([0:n+1],ones(n+2,1),'r-');


% Generate raw data figure
subplot(2,1,2);
scatter(x,Freq1,25,'MarkerEdgeColor','k','MarkerFaceColor','#bc5090');hold on;
scatter(x,Freq2,25,'MarkerEdgeColor','k','MarkerFaceColor','#ffa600');
ylim([0 1.1]);xlim([-1 63]);

% Set xtick labels
xticks(1:n);
xticklabels(labels);
a = get(gca,'XTickLabel'); set(gca,'XTickLabel',a,'fontsize',9);
xtickangle(90);
ylabel('Synonymous codon usage','FontSize',font);
title('Raw data','FontSize',font+1);
legend(lgd,'FontSize',font);

end